### PR TITLE
Add Middleware + tests

### PR DESCRIPTION
**Pull request by brianegan**
Hey there! Thanks for the cool implementation of Redux :) I wanted to start using Redux.dart for some Flutter apps I've been playing with, but found that the library was missing Middleware (which I've found to be pretty critical in other ecosystems).

Therefore, I took your library and added Middleware in! I've also changed up `Reducer` from a proper class to a `typedef` since it gave the same generics guarantees yet made the definition of the "class" more concise / flexible. 

Finally, I added tests so that everything is covered! Let me know whatcha think :)

### CODE REVIEW

**Comment by johnpryan** [comment]
Awesome - thanks for the contribution - I'll review this tonight and hopefully get it merged ASAP.

Thanks!

**Comment by johnpryan** [comment]
I found some time to review the code and make some additional changes.  Overall, the middleware and tests are solid changes that I would like to merge.

Additionally, I would like to to keep the API for Reducer and CombinedReducer a class-based API, e.g:

```
class Counter extends Reducer<AppState, AppAction> {
  reduce(AppState state, AppAction action) {
    switch (action) {
      case AppAction.increment:
        return new AppState(state.count + 1, state.clickCount);
      case AppAction.decrement:
        return new AppState(state.count - 1, state.clickCount);
      default:
        return state;
    }
  }
}
```

as opposed to the function-based API:

```
Reducer<AppState, AppAction> counterReducer =
    (AppState state, AppAction action) {
  switch (action) {
    case AppAction.increment:
      return new AppState(state.count + 1, state.clickCount);
    case AppAction.decrement:
      return new AppState(state.count - 1, state.clickCount);
    default:
      return state;
  }
};
```

The main reason for this is stylistic, but it also allows `dartanalyzer` to better enforce the generics without strong mode.

Let me know what you think, I made a [PR to your branch](https://github.com/brianegan/redux.dart/pull/1) with the changes.

**Comment by brianegan** [comment]
Cool, thanks for the feedback! 

Fair point about the `dartanalyzer` only being supported in certain cases in strong mode! That said, I think the only place you'd lose the type analysis would be in `combineReducers`. You still get it in the middleware and reducers themselves, and a functional style would give more flexible options for reducer & middleware composition down the line. But overall, I'm not that picky. It's your library, do your thing :)

Your PR looks good from my side. How shall we proceed from here? Shall I leave it in your hands to finish off your preferred changes?

**Comment by johnpryan** [comment]
I'm not sure what maintainers typically do, but I would like your commit to be part of the commit history.

Could you merge my commit into your branch? (which will add my changes to this PR.) Then I'll merge them both as part of this PR.

**Comment by brianegan** [comment]
Cool, that's all set! Also, if you want to do any last minute changes, you can simply pull this down, make any final changes, then merge normally. My info will still be in the history!

Thanks again for the library and letting me contribute :)

**Comment by johnpryan** [comment]
Everything looks good.  Merging...

**Pull request merged**
